# this_file: /root/repo/.swiftlint.yml

# SwiftLint configuration for Dragoboo
# https://github.com/realm/SwiftLint

# Directories to include in linting
included:
  - Sources/
  - Tests/

# Directories to exclude from linting
excluded:
  - .build/
  - build/
  - archives/
  - coverage/
  - reports/
  - Package.swift

# Rules to disable
disabled_rules:
  - trailing_comma  # Allow trailing commas in arrays/dictionaries
  - todo           # Allow TODO comments during development

# Rules to enable (opt-in)
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - no_space_in_method_call
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length: 1
  max_length: 40
  excluded:
    - id
    - x
    - y
    - dx
    - dy
    - fn
    - ax
    - ay
    - ui
    - os

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - Row
    - Tag
    - Key
    - App
    - UI

nesting:
  type_level: 2
  function_level: 3

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: warning

file_header:
  required_pattern: |
                    \/\/ this_file: .*\.swift

# Custom rules for specific patterns
custom_rules:
  no_print:
    name: "No print statements"
    regex: "\\bprint\\("
    message: "Use proper logging instead of print()"
    severity: warning
  
  no_force_unwrapping_in_tests:
    name: "No force unwrapping in tests"
    regex: "\\!(?![=!])"
    match_kinds:
      - identifier
    included: ".*Tests\\.swift"
    message: "Use XCTUnwrap or proper error handling in tests"
    severity: warning
  
  no_hardcoded_strings:
    name: "No hardcoded strings"
    regex: "\\\"[^\\\"]{20,}\\\""
    message: "Consider using constants for long strings"
    severity: warning
  
  proper_spacing_around_operators:
    name: "Proper spacing around operators"
    regex: "\\S(\\+|\\-|\\*|\\/|=|==|!=|<=|>=|<|>|&&|\\|\\||\\?\\?|\\?:|\\+=|\\-=|\\*=|\\/=)\\S"
    message: "Operators should have spaces around them"
    severity: warning

# Reporter configuration
reporter: "xcode"

# Analyzer rules (require full project analysis)
analyzer_rules:
  - unused_declaration
  - unused_import