// this_file: /root/repo/Sources/DragobooCore/Version.swift
// Generated by scripts/version.sh - DO NOT EDIT MANUALLY

import Foundation

/// Version information for Dragoboo
public struct Version {
    /// The semantic version string (e.g., "1.0.0")
    public let semver: String
    
    /// The git commit hash
    public let commit: String
    
    /// The build date
    public let buildDate: String
    
    /// Whether this is a development build
    public let isDevelopment: Bool
    
    /// Current version instance
    public static let current = Version(
        semver: VersionInfo.semver,
        commit: VersionInfo.commit,
        buildDate: VersionInfo.buildDate,
        isDevelopment: VersionInfo.isDevelopment
    )
    
    /// Full version string including build info
    public var fullVersion: String {
        if isDevelopment {
            return "\(semver)-dev+\(commit.prefix(7))"
        } else {
            return semver
        }
    }
    
    /// Version info for display
    public var displayString: String {
        return "v\(fullVersion) (\(buildDate))"
    }
}

/// Internal version info that gets populated by build scripts
internal struct VersionInfo {
    static let semver = "1.0.0"
    static let commit = "92cadbd64e052237a5a5b61c558862c857656667"
    static let buildDate = "2025-07-17 14:19:57 UTC"
    static let isDevelopment = true
}
